#!/usr/bin/env python3
"""
Import Speciedex MariaDB logical shards into canonical JSONL.

Expected location:
    static/tools/database/import-mariadb.py

The importer reads MariaDB-compatible logical SQL shards generated by
build-mariadb-shards.py, validates manifest metadata and checksums, parses
INSERT rows without requiring a running MariaDB server, and writes a
deterministic canonical JSONL stream plus an import summary.

Copyright (c) 2026 Speciedex.org & ZZX-Labs R&D
Licensed under the MIT License.
"""

from __future__ import annotations

import argparse
import contextlib
import gzip
import json
import logging
import math
import os
import re
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable, Iterator, Mapping, Sequence, TextIO

from common import (
    SQLITE_COLUMNS,
    atomic_write_json,
    clean_text,
    load_manifest,
    sha256_file,
    stable_json,
    utc_now,
    validate_canonical_record,
    write_jsonl,
)


EXIT_SUCCESS = 0
EXIT_INVALID = 1
EXIT_CONFIGURATION = 2
EXIT_INTERRUPTED = 130

DEFAULT_MARIADB_ROOT = Path("static/data/db/mariadb")
DEFAULT_OUTPUT = Path(
    "static/data/taxonomy/imported/mariadb-import.jsonl"
)
DEFAULT_REJECTED = Path(
    "static/data/taxonomy/imported/mariadb-import-rejected.jsonl"
)
DEFAULT_SUMMARY = Path(
    "static/data/taxonomy/imported/mariadb-import-summary.json"
)

INSERT_PREFIX_RE = re.compile(
    r"^\s*INSERT\s+INTO\s+`?taxa`?\s*\((.*?)\)\s*VALUES\s*$",
    re.IGNORECASE,
)
UPSERT_RE = re.compile(
    r"^\s*ON\s+DUPLICATE\s+KEY\s+UPDATE\b",
    re.IGNORECASE,
)
SHARD_HEADER_RE = re.compile(r"^--\s*Speciedex\b", re.IGNORECASE)


class MariaDBImportError(RuntimeError):
    def __init__(self, message: str, exit_code: int = EXIT_INVALID) -> None:
        super().__init__(message)
        self.exit_code = exit_code


@dataclass
class ShardImportResult:
    shard_id: str
    path: str
    exists: bool = False
    manifest_records: int | None = None
    imported_records: int = 0
    rejected_records: int = 0
    manifest_sha256: str = ""
    actual_sha256: str = ""
    checksum_ok: bool | None = None
    header_ok: bool | None = None
    column_order_ok: bool | None = None
    transaction_ok: bool | None = None
    issues: list[str] = field(default_factory=list)
    duration_seconds: float = 0.0


def human_duration(seconds: float) -> str:
    seconds = max(0, int(round(seconds)))
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


def integer_or_none(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, str) and re.fullmatch(r"-?\d+", value.strip()):
        return int(value.strip())
    return None


def shard_id(shard: Mapping[str, Any]) -> str:
    return clean_text(shard.get("id") or shard.get("shard_id"))


def shard_path(shard: Mapping[str, Any]) -> str:
    return clean_text(shard.get("path") or shard.get("filename"))


def safe_path(root: Path, relative: str) -> Path:
    path = (root / relative).resolve()
    try:
        path.relative_to(root.resolve())
    except ValueError as error:
        raise MariaDBImportError(
            f"Manifest path escapes MariaDB root: {relative}",
            EXIT_CONFIGURATION,
        ) from error
    return path


@contextlib.contextmanager
def open_sql_text(path: Path) -> Iterator[TextIO]:
    if path.name.casefold().endswith(".gz"):
        with gzip.open(path, "rt", encoding="utf-8", newline="") as handle:
            yield handle
    else:
        with path.open("r", encoding="utf-8", newline="") as handle:
            yield handle


def parse_column_list(text: str) -> list[str]:
    columns: list[str] = []
    for item in text.split(","):
        column = item.strip().strip("`").strip('"')
        if column:
            columns.append(column)
    return columns


def split_sql_values(row: str) -> list[str]:
    """
    Split a MariaDB VALUES row while respecting quoted strings and escapes.

    Supports:
      * SQL single-quoted strings
      * doubled single quotes
      * backslash escapes
      * commas inside strings
      * NULL and numeric literals
    """
    values: list[str] = []
    current: list[str] = []
    quoted = False
    index = 0

    while index < len(row):
        char = row[index]

        if quoted:
            current.append(char)

            if char == "\\":
                index += 1
                if index < len(row):
                    current.append(row[index])
            elif char == "'":
                if index + 1 < len(row) and row[index + 1] == "'":
                    index += 1
                    current.append(row[index])
                else:
                    quoted = False
        else:
            if char == "'":
                quoted = True
                current.append(char)
            elif char == ",":
                values.append("".join(current).strip())
                current = []
            else:
                current.append(char)

        index += 1

    if quoted:
        raise ValueError("unterminated SQL string literal")

    values.append("".join(current).strip())
    return values


def decode_sql_string(value: str) -> str:
    inner = value[1:-1]
    result: list[str] = []
    index = 0

    while index < len(inner):
        char = inner[index]

        if char == "'" and index + 1 < len(inner) and inner[index + 1] == "'":
            result.append("'")
            index += 2
            continue

        if char == "\\" and index + 1 < len(inner):
            index += 1
            escaped = inner[index]
            mapping = {
                "0": "\0",
                "b": "\b",
                "n": "\n",
                "r": "\r",
                "t": "\t",
                "Z": "\x1a",
                "\\": "\\",
                "'": "'",
                '"': '"',
            }
            result.append(mapping.get(escaped, escaped))
            index += 1
            continue

        result.append(char)
        index += 1

    return "".join(result)


def decode_sql(value: str) -> Any:
    text = value.strip()
    upper = text.upper()

    if upper == "NULL":
        return None
    if upper == "TRUE":
        return True
    if upper == "FALSE":
        return False

    if len(text) >= 2 and text.startswith("'") and text.endswith("'"):
        return decode_sql_string(text)

    try:
        if re.fullmatch(r"[+-]?\d+", text):
            return int(text)
        number = float(text)
        return number if math.isfinite(number) else None
    except ValueError:
        return text


def strip_row_wrapper(text: str) -> str:
    stripped = text.strip().rstrip(",").rstrip(";").strip()
    if not stripped.startswith("(") or not stripped.endswith(")"):
        raise ValueError("expected parenthesized SQL VALUES row")
    return stripped[1:-1]


def iter_insert_rows(
    path: Path,
) -> Iterator[tuple[int, list[str], list[Any]]]:
    """
    Yield (line_number, columns, values) from generated taxa INSERT blocks.

    Generated Speciedex logical shards place each complete VALUES row on one
    physical line. The parser intentionally rejects unsupported SQL rather than
    silently guessing.
    """
    columns: list[str] = []
    collecting = False

    with open_sql_text(path) as handle:
        for line_number, line in enumerate(handle, 1):
            stripped = line.strip()

            if not stripped:
                continue

            match = INSERT_PREFIX_RE.match(stripped)
            if match:
                columns = parse_column_list(match.group(1))
                collecting = True
                continue

            if not collecting:
                continue

            if UPSERT_RE.match(stripped):
                collecting = False
                columns = []
                continue

            if not stripped.startswith("("):
                continue

            inner = strip_row_wrapper(stripped)
            values = [decode_sql(item) for item in split_sql_values(inner)]
            yield line_number, columns, values


def normalize_imported_record(
    columns: Sequence[str],
    values: Sequence[Any],
) -> dict[str, Any]:
    if len(columns) != len(values):
        raise ValueError(
            f"column/value count mismatch: {len(columns)} columns, "
            f"{len(values)} values"
        )

    record = dict(zip(columns, values))

    missing = [column for column in SQLITE_COLUMNS if column not in record]
    if missing:
        raise ValueError(
            "logical shard row is missing canonical column(s): "
            + ", ".join(missing)
        )

    return {column: record.get(column) for column in SQLITE_COLUMNS}


class MariaDBImporter:
    def __init__(self, args: argparse.Namespace) -> None:
        self.args = args
        self.root = args.mariadb_root.resolve()
        self.output = args.output.resolve()
        self.rejected_path = args.rejected.resolve()
        self.summary_path = args.summary.resolve()
        self.logger = logging.getLogger("speciedex.database.import_mariadb")
        self.started = time.monotonic()
        self.results: list[ShardImportResult] = []
        self.issues: list[str] = []
        self.rejected: list[dict[str, Any]] = []
        self.records: list[dict[str, Any]] = []
        self.seen_ids: set[str] = set()

    def configure_logging(self) -> None:
        level = logging.DEBUG if self.args.verbose else logging.INFO
        if self.args.quiet:
            level = logging.WARNING

        logging.basicConfig(
            level=level,
            format="%(asctime)s %(levelname)s %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
        )

    def add_issue(
        self,
        message: str,
        result: ShardImportResult | None = None,
    ) -> None:
        self.issues.append(message)
        if result is not None:
            result.issues.append(message)

    def validate(self) -> None:
        if not self.root.exists():
            raise MariaDBImportError(
                f"MariaDB root does not exist: {self.root}",
                EXIT_CONFIGURATION,
            )
        if not self.root.is_dir():
            raise MariaDBImportError(
                f"MariaDB root is not a directory: {self.root}",
                EXIT_CONFIGURATION,
            )

        manifest = self.root / "manifest.json"
        if not manifest.is_file():
            raise MariaDBImportError(
                f"MariaDB manifest not found: {manifest}",
                EXIT_CONFIGURATION,
            )

    def validate_header(self, path: Path, result: ShardImportResult) -> None:
        first_nonempty = ""
        saw_start = False
        saw_commit = False

        with open_sql_text(path) as handle:
            for line in handle:
                stripped = line.strip()
                if not stripped:
                    continue
                if not first_nonempty:
                    first_nonempty = stripped
                upper = stripped.upper()
                if upper.startswith("START TRANSACTION"):
                    saw_start = True
                elif upper.startswith("COMMIT"):
                    saw_commit = True

        result.header_ok = bool(SHARD_HEADER_RE.match(first_nonempty))
        result.transaction_ok = saw_start and saw_commit

        if not result.header_ok:
            self.add_issue(f"Invalid Speciedex shard header: {path}", result)
        if not result.transaction_ok:
            self.add_issue(
                f"Incomplete transaction framing in shard: {path}",
                result,
            )

    def reject(
        self,
        *,
        path: Path,
        shard_identifier: str,
        line_number: int,
        reason: str,
        columns: Sequence[str] | None = None,
        values: Sequence[Any] | None = None,
    ) -> None:
        self.rejected.append(
            {
                "shard_id": shard_identifier,
                "source_file": path.as_posix(),
                "line_number": line_number,
                "reason": reason,
                "columns": list(columns or ()),
                "values": list(values or ()),
            }
        )

    def import_shard(
        self,
        shard: Mapping[str, Any],
    ) -> ShardImportResult:
        started = time.monotonic()
        identifier = shard_id(shard)
        relative = shard_path(shard)

        result = ShardImportResult(
            shard_id=identifier,
            path=relative,
            manifest_records=integer_or_none(
                shard.get("records", shard.get("rows"))
            ),
            manifest_sha256=clean_text(shard.get("sha256")),
        )

        if not identifier:
            self.add_issue("Manifest shard is missing an id.", result)
        if not relative:
            self.add_issue(
                f"MariaDB shard {identifier or '<unknown>'} has no path.",
                result,
            )
            return result

        path = safe_path(self.root, relative)
        result.path = path.as_posix()
        result.exists = path.is_file()

        if not result.exists:
            self.add_issue(f"Missing MariaDB shard: {path}", result)
            return result

        result.actual_sha256 = sha256_file(path)
        if result.manifest_sha256:
            result.checksum_ok = (
                result.actual_sha256.casefold()
                == result.manifest_sha256.casefold()
            )
            if not result.checksum_ok:
                self.add_issue(f"Checksum mismatch: {path}", result)
                if self.args.strict:
                    result.duration_seconds = round(
                        time.monotonic() - started,
                        6,
                    )
                    return result

        try:
            self.validate_header(path, result)
        except (OSError, EOFError, UnicodeError) as error:
            self.add_issue(f"Unable to read shard {path}: {error}", result)
            return result

        expected_columns = list(SQLITE_COLUMNS)

        try:
            for line_number, columns, values in iter_insert_rows(path):
                try:
                    result.column_order_ok = columns == expected_columns
                    if not result.column_order_ok:
                        raise ValueError(
                            "column order differs from canonical SQLITE_COLUMNS"
                        )

                    record = normalize_imported_record(columns, values)
                    validation_errors = validate_canonical_record(record)
                    if validation_errors:
                        raise ValueError("; ".join(validation_errors))

                    identifier_value = clean_text(
                        record.get("speciedex_id")
                    )
                    if self.args.deduplicate and identifier_value in self.seen_ids:
                        if self.args.duplicate_policy == "error":
                            raise ValueError(
                                f"duplicate speciedex_id: {identifier_value}"
                            )
                        if self.args.duplicate_policy == "first":
                            continue
                        if self.args.duplicate_policy == "last":
                            self.records = [
                                existing
                                for existing in self.records
                                if clean_text(existing.get("speciedex_id"))
                                != identifier_value
                            ]

                    if identifier_value:
                        self.seen_ids.add(identifier_value)

                    self.records.append(record)
                    result.imported_records += 1

                except Exception as error:
                    result.rejected_records += 1
                    self.reject(
                        path=path,
                        shard_identifier=identifier,
                        line_number=line_number,
                        reason=str(error),
                        columns=columns,
                        values=values,
                    )
                    if self.args.strict:
                        raise MariaDBImportError(
                            f"{path}:{line_number}: {error}"
                        ) from error

        except (OSError, EOFError, UnicodeError, ValueError) as error:
            self.add_issue(f"Failed parsing shard {path}: {error}", result)
            if self.args.strict:
                raise MariaDBImportError(
                    f"Failed parsing shard {path}: {error}"
                ) from error

        if (
            result.manifest_records is not None
            and result.imported_records + result.rejected_records
            != result.manifest_records
        ):
            self.add_issue(
                f"Manifest row-count mismatch for {path}: "
                f"manifest={result.manifest_records}, "
                f"parsed={result.imported_records + result.rejected_records}",
                result,
            )

        result.duration_seconds = round(time.monotonic() - started, 6)
        return result

    def write_outputs(self) -> None:
        if self.args.sort:
            self.records.sort(
                key=lambda record: clean_text(record.get("speciedex_id"))
            )

        if self.args.dry_run:
            self.logger.info(
                "Dry run: would write %d imported and %d rejected records.",
                len(self.records),
                len(self.rejected),
            )
            return

        write_jsonl(
            self.output,
            self.records,
            gzip_output=self.output.name.casefold().endswith(".gz"),
        )
        write_jsonl(
            self.rejected_path,
            self.rejected,
            gzip_output=self.rejected_path.name.casefold().endswith(".gz"),
        )

        elapsed = time.monotonic() - self.started
        summary = {
            "schema_version": 2,
            "generated_at": utc_now(),
            "mariadb_root": self.root.as_posix(),
            "output": self.output.as_posix(),
            "rejected_output": self.rejected_path.as_posix(),
            "valid": not self.issues,
            "duration_seconds": round(elapsed, 6),
            "duration": human_duration(elapsed),
            "options": {
                "strict": self.args.strict,
                "verify_checksums": self.args.verify_checksums,
                "deduplicate": self.args.deduplicate,
                "duplicate_policy": self.args.duplicate_policy,
                "sort": self.args.sort,
            },
            "totals": {
                "shards": len(self.results),
                "imported_records": len(self.records),
                "rejected_records": len(self.rejected),
                "issues": len(self.issues),
            },
            "issues": self.issues,
            "shards": [asdict(result) for result in self.results],
        }
        atomic_write_json(self.summary_path, summary)

    def verify_output(self) -> None:
        if self.args.dry_run or not self.args.verify_output:
            return

        imported = 0
        with self.output.open("rb") as handle:
            if self.output.name.casefold().endswith(".gz"):
                opener = gzip.open
                with opener(self.output, "rt", encoding="utf-8") as text_handle:
                    imported = sum(1 for line in text_handle if line.strip())
            else:
                imported = sum(1 for line in handle if line.strip())

        if imported != len(self.records):
            raise MariaDBImportError(
                f"Output count mismatch: expected {len(self.records)}, "
                f"found {imported}"
            )

    def run(self) -> int:
        self.configure_logging()

        try:
            self.validate()
            manifest = load_manifest(self.root / "manifest.json")
            shards = manifest.get("shards", [])

            if not isinstance(shards, list):
                raise MariaDBImportError(
                    "MariaDB manifest shards must be an array.",
                    EXIT_CONFIGURATION,
                )

            seen_shard_ids: set[str] = set()
            for position, shard in enumerate(shards, 1):
                if not isinstance(shard, Mapping):
                    self.add_issue(
                        f"Manifest shard {position} is not an object."
                    )
                    continue

                identifier = shard_id(shard)
                if identifier in seen_shard_ids:
                    self.add_issue(
                        f"Duplicate manifest shard id: {identifier}"
                    )
                    continue
                if identifier:
                    seen_shard_ids.add(identifier)

                result = self.import_shard(shard)
                self.results.append(result)

            self.write_outputs()
            self.verify_output()

        except KeyboardInterrupt:
            self.logger.error("MariaDB import interrupted.")
            return EXIT_INTERRUPTED
        except MariaDBImportError as error:
            self.logger.error("%s", error)
            return error.exit_code
        except Exception as error:
            self.logger.error("MariaDB import failed: %s", error)
            if self.args.verbose:
                self.logger.exception("Detailed failure")
            return EXIT_CONFIGURATION

        if self.issues and self.args.fail_on_issue:
            for issue in self.issues:
                self.logger.error("%s", issue)
            return EXIT_INVALID

        self.logger.info(
            "Imported %d records from %d MariaDB logical shard(s) with "
            "%d rejected records in %s.",
            len(self.records),
            len(self.results),
            len(self.rejected),
            human_duration(time.monotonic() - self.started),
        )
        return EXIT_SUCCESS


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Import Speciedex MariaDB logical shards into canonical JSONL."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--mariadb-root",
        type=Path,
        default=DEFAULT_MARIADB_ROOT,
        help="Directory containing logical SQL shards and manifest.json.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Canonical imported JSONL destination.",
    )
    parser.add_argument(
        "--rejected",
        type=Path,
        default=DEFAULT_REJECTED,
        help="Rejected-row JSONL destination.",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=DEFAULT_SUMMARY,
        help="Import-summary JSON destination.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Stop immediately on checksum, parsing, or validation errors.",
    )
    parser.add_argument(
        "--verify-checksums",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Verify shard SHA-256 checksums when present in the manifest.",
    )
    parser.add_argument(
        "--verify-output",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Re-read the generated output and verify its record count.",
    )
    parser.add_argument(
        "--deduplicate",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Deduplicate records by speciedex_id.",
    )
    parser.add_argument(
        "--duplicate-policy",
        choices=("first", "last", "error"),
        default="last",
        help="Policy applied when deduplication finds duplicate IDs.",
    )
    parser.add_argument(
        "--sort",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Sort output deterministically by speciedex_id.",
    )
    parser.add_argument(
        "--fail-on-issue",
        action="store_true",
        help="Return a nonzero status when nonfatal issues were recorded.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse and validate without writing output files.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress informational logging.",
    )

    args = parser.parse_args(argv)

    if args.verbose and args.quiet:
        parser.error("--verbose and --quiet cannot be used together.")

    return args


def main(argv: Sequence[str] | None = None) -> int:
    return MariaDBImporter(parse_args(argv)).run()


if __name__ == "__main__":
    raise SystemExit(main())
