#!/usr/bin/env python3
"""
Import Speciedex MariaDB logical shards into canonical JSONL.

Expected location:
    static/tools/database/import-mariadb.py

The importer reads manifest-managed MariaDB-compatible logical SQL shards
generated by build-mariadb-shards.py, validates safe paths, checksums, file
sizes, headers, transaction framing, column order, and row counts, then writes
a deterministic canonical JSONL review stream with rejected-row and summary
reports.

This tool does not require a running MariaDB server and does not overwrite the
canonical taxonomy archive directly. Imported records must still be reconciled
and validated before becoming authoritative.

Copyright (c) 2026 Speciedex.org & ZZX-Labs R&D
Licensed under the MIT License.
"""

from __future__ import annotations

import argparse
import contextlib
import gzip
import json
import logging
import math
import re
import tempfile
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterator, Mapping, Sequence, TextIO

from common import (
    SQLITE_COLUMNS,
    atomic_write_json,
    clean_text,
    load_manifest,
    sha256_file,
    stable_json,
    utc_now,
    validate_canonical_record,
    validate_manifest,
    write_jsonl,
)


EXIT_SUCCESS = 0
EXIT_INVALID = 1
EXIT_CONFIGURATION = 2
EXIT_INTERRUPTED = 130

DEFAULT_MARIADB_ROOT = Path("static/data/db/mariadb")
DEFAULT_OUTPUT = Path(
    "static/data/taxonomy/imported/mariadb-import.jsonl"
)
DEFAULT_REJECTED = Path(
    "static/data/taxonomy/imported/mariadb-import-rejected.jsonl"
)
DEFAULT_SUMMARY = Path(
    "static/data/taxonomy/imported/mariadb-import-summary.json"
)

MANIFEST_FILENAME = "manifest.json"
SCHEMA_FILENAME = "schema.sql"

INSERT_PREFIX_RE = re.compile(
    r"^\s*INSERT\s+INTO\s+`?taxa`?\s*\((.*?)\)\s*VALUES\s*$",
    re.IGNORECASE,
)
UPSERT_RE = re.compile(
    r"^\s*ON\s+DUPLICATE\s+KEY\s+UPDATE\b",
    re.IGNORECASE,
)
SHARD_HEADER_RE = re.compile(
    r"^--\s*Speciedex\s+MariaDB\s+logical\s+shard\s*$",
    re.IGNORECASE,
)


class MariaDBImportError(RuntimeError):
    def __init__(self, message: str, exit_code: int = EXIT_INVALID) -> None:
        super().__init__(message)
        self.exit_code = exit_code


@dataclass
class ShardImportResult:
    shard_id: str
    path: str
    exists: bool = False
    manifest_records: int | None = None
    parsed_records: int = 0
    imported_records: int = 0
    rejected_records: int = 0
    duplicate_records: int = 0
    manifest_bytes: int | None = None
    actual_bytes: int | None = None
    size_ok: bool | None = None
    manifest_sha256: str = ""
    actual_sha256: str = ""
    checksum_ok: bool | None = None
    header_ok: bool | None = None
    shard_header_id: str = ""
    header_id_ok: bool | None = None
    column_order_ok: bool | None = None
    transaction_ok: bool | None = None
    row_count_ok: bool | None = None
    issues: list[str] = field(default_factory=list)
    duration_seconds: float = 0.0


def human_duration(seconds: float) -> str:
    seconds = max(0, int(round(seconds)))
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


def integer_or_none(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, str) and re.fullmatch(r"-?\d+", value.strip()):
        return int(value.strip())
    return None


def shard_id(shard: Mapping[str, Any]) -> str:
    return clean_text(shard.get("id") or shard.get("shard_id"))


def shard_path(shard: Mapping[str, Any]) -> str:
    return clean_text(shard.get("path") or shard.get("filename"))


def safe_path(root: Path, relative: str) -> Path:
    if not relative:
        raise MariaDBImportError(
            "Manifest shard path cannot be empty.",
            EXIT_CONFIGURATION,
        )

    candidate = Path(relative)
    if candidate.is_absolute():
        raise MariaDBImportError(
            f"Manifest shard path must be relative: {relative}",
            EXIT_CONFIGURATION,
        )

    resolved_root = root.resolve()
    resolved = (resolved_root / candidate).resolve()

    try:
        resolved.relative_to(resolved_root)
    except ValueError as error:
        raise MariaDBImportError(
            f"Manifest path escapes MariaDB root: {relative}",
            EXIT_CONFIGURATION,
        ) from error

    return resolved


@contextlib.contextmanager
def open_sql_text(path: Path) -> Iterator[TextIO]:
    if path.name.casefold().endswith(".gz"):
        with gzip.open(
            path,
            "rt",
            encoding="utf-8",
            newline="",
        ) as handle:
            yield handle
    else:
        with path.open(
            "r",
            encoding="utf-8",
            newline="",
        ) as handle:
            yield handle


def parse_column_list(text: str) -> list[str]:
    columns: list[str] = []

    for item in text.split(","):
        column = item.strip().strip("`").strip('"')
        if not column:
            raise ValueError("empty column in INSERT column list")
        columns.append(column)

    if len(set(columns)) != len(columns):
        raise ValueError("duplicate column in INSERT column list")

    return columns


def split_sql_values(row: str) -> list[str]:
    """
    Split one MariaDB VALUES tuple while respecting quoted strings.

    Supports SQL single-quoted strings, doubled single quotes, backslash
    escapes, commas inside strings, NULL, booleans, and numeric literals.
    """
    values: list[str] = []
    current: list[str] = []
    quoted = False
    index = 0

    while index < len(row):
        character = row[index]

        if quoted:
            current.append(character)

            if character == "\\":
                index += 1
                if index < len(row):
                    current.append(row[index])

            elif character == "'":
                if (
                    index + 1 < len(row)
                    and row[index + 1] == "'"
                ):
                    index += 1
                    current.append(row[index])
                else:
                    quoted = False

        else:
            if character == "'":
                quoted = True
                current.append(character)

            elif character == ",":
                values.append("".join(current).strip())
                current = []

            else:
                current.append(character)

        index += 1

    if quoted:
        raise ValueError("unterminated SQL string literal")

    values.append("".join(current).strip())
    return values


def decode_sql_string(value: str) -> str:
    if len(value) < 2 or not (
        value.startswith("'") and value.endswith("'")
    ):
        raise ValueError("expected SQL single-quoted string")

    inner = value[1:-1]
    result: list[str] = []
    index = 0

    while index < len(inner):
        character = inner[index]

        if (
            character == "'"
            and index + 1 < len(inner)
            and inner[index + 1] == "'"
        ):
            result.append("'")
            index += 2
            continue

        if character == "\\" and index + 1 < len(inner):
            index += 1
            escaped = inner[index]
            mapping = {
                "0": "\0",
                "b": "\b",
                "n": "\n",
                "r": "\r",
                "t": "\t",
                "Z": "\x1a",
                "\\": "\\",
                "'": "'",
                '"': '"',
            }
            result.append(mapping.get(escaped, escaped))
            index += 1
            continue

        result.append(character)
        index += 1

    return "".join(result)


def decode_sql(value: str) -> Any:
    text = value.strip()
    upper = text.upper()

    if upper == "NULL":
        return None
    if upper == "TRUE":
        return True
    if upper == "FALSE":
        return False

    if len(text) >= 2 and text.startswith("'") and text.endswith("'"):
        return decode_sql_string(text)

    if re.fullmatch(r"[+-]?\d+", text):
        return int(text)

    if re.fullmatch(
        r"[+-]?(?:\d+\.\d*|\.\d+|\d+)(?:[eE][+-]?\d+)?",
        text,
    ):
        number = float(text)
        return number if math.isfinite(number) else None

    raise ValueError(f"unsupported SQL literal: {text!r}")


def strip_row_wrapper(text: str) -> str:
    stripped = text.strip()

    if stripped.endswith(",") or stripped.endswith(";"):
        stripped = stripped[:-1].rstrip()

    if not stripped.startswith("(") or not stripped.endswith(")"):
        raise ValueError("expected parenthesized SQL VALUES row")

    return stripped[1:-1]


def iter_insert_rows(
    path: Path,
) -> Iterator[tuple[int, list[str], list[Any]]]:
    """
    Yield (line_number, columns, values) from generated taxa INSERT blocks.

    Speciedex logical shards place each complete VALUES tuple on one physical
    line. Unsupported or malformed SQL is rejected rather than guessed.
    """
    columns: list[str] = []
    collecting = False
    saw_insert = False

    with open_sql_text(path) as handle:
        for line_number, line in enumerate(handle, 1):
            stripped = line.strip()

            if not stripped:
                continue

            match = INSERT_PREFIX_RE.match(stripped)
            if match:
                if collecting:
                    raise ValueError(
                        f"line {line_number}: nested INSERT block"
                    )
                columns = parse_column_list(match.group(1))
                collecting = True
                saw_insert = True
                continue

            if UPSERT_RE.match(stripped):
                if not collecting:
                    raise ValueError(
                        f"line {line_number}: UPSERT outside INSERT block"
                    )
                collecting = False
                columns = []
                continue

            if not collecting:
                continue

            if not stripped.startswith("("):
                raise ValueError(
                    f"line {line_number}: unexpected SQL inside VALUES block"
                )

            inner = strip_row_wrapper(stripped)
            values = [
                decode_sql(item)
                for item in split_sql_values(inner)
            ]
            yield line_number, list(columns), values

    if collecting:
        raise ValueError("unterminated INSERT block")

    if not saw_insert:
        raise ValueError("no taxa INSERT statements found")


def normalize_imported_record(
    columns: Sequence[str],
    values: Sequence[Any],
) -> dict[str, Any]:
    if len(columns) != len(values):
        raise ValueError(
            f"column/value count mismatch: "
            f"{len(columns)} columns, {len(values)} values"
        )

    record = dict(zip(columns, values))
    missing = [
        column
        for column in SQLITE_COLUMNS
        if column not in record
    ]

    if missing:
        raise ValueError(
            "logical shard row is missing canonical column(s): "
            + ", ".join(missing)
        )

    unexpected = [
        column
        for column in columns
        if column not in SQLITE_COLUMNS
    ]
    if unexpected:
        raise ValueError(
            "logical shard row contains unexpected column(s): "
            + ", ".join(unexpected)
        )

    return {
        column: record.get(column)
        for column in SQLITE_COLUMNS
    }


def verify_jsonl_count(path: Path) -> int:
    opener = (
        gzip.open
        if path.name.casefold().endswith(".gz")
        else open
    )
    count = 0

    with opener(path, "rt", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            stripped = line.strip()
            if not stripped:
                continue

            try:
                value = json.loads(stripped)
            except json.JSONDecodeError as error:
                raise MariaDBImportError(
                    f"{path}:{line_number}: invalid JSON: {error}"
                ) from error

            if not isinstance(value, Mapping):
                raise MariaDBImportError(
                    f"{path}:{line_number}: expected JSON object"
                )

            count += 1

    return count


class MariaDBImporter:
    def __init__(self, args: argparse.Namespace) -> None:
        self.args = args
        self.root = args.mariadb_root.resolve()
        self.manifest_path = (
            args.manifest or self.root / MANIFEST_FILENAME
        ).resolve()
        self.output = args.output.resolve()
        self.rejected_path = args.rejected.resolve()
        self.summary_path = args.summary.resolve()
        self.logger = logging.getLogger(
            "speciedex.database.import_mariadb"
        )
        self.started = time.monotonic()

        self.results: list[ShardImportResult] = []
        self.issues: list[str] = []
        self.rejected: list[dict[str, Any]] = []
        self.records_by_id: dict[str, dict[str, Any]] = {}
        self.record_order: list[str] = []
        self.anonymous_records: list[dict[str, Any]] = []
        self.total_accepted_rows = 0

    def configure_logging(self) -> None:
        level = logging.DEBUG if self.args.verbose else logging.INFO
        if self.args.quiet:
            level = logging.WARNING

        logging.basicConfig(
            level=level,
            format="%(asctime)s %(levelname)s %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
        )

    def add_issue(
        self,
        message: str,
        result: ShardImportResult | None = None,
    ) -> None:
        self.issues.append(message)
        if result is not None:
            result.issues.append(message)

    def validate(self) -> None:
        if not self.root.exists():
            raise MariaDBImportError(
                f"MariaDB root does not exist: {self.root}",
                EXIT_CONFIGURATION,
            )

        if not self.root.is_dir():
            raise MariaDBImportError(
                f"MariaDB root is not a directory: {self.root}",
                EXIT_CONFIGURATION,
            )

        if not self.manifest_path.is_file():
            raise MariaDBImportError(
                f"MariaDB manifest not found: {self.manifest_path}",
                EXIT_CONFIGURATION,
            )

        try:
            self.manifest_path.relative_to(self.root)
        except ValueError:
            if not self.args.allow_external_manifest:
                raise MariaDBImportError(
                    "Manifest must be beneath --mariadb-root unless "
                    "--allow-external-manifest is supplied.",
                    EXIT_CONFIGURATION,
                )

        destinations = {
            self.output,
            self.rejected_path,
            self.summary_path,
        }
        if len(destinations) != 3:
            raise MariaDBImportError(
                "--output, --rejected, and --summary must be distinct paths.",
                EXIT_CONFIGURATION,
            )

        for destination in destinations:
            destination.parent.mkdir(parents=True, exist_ok=True)
            probe: Path | None = None

            try:
                with tempfile.NamedTemporaryFile(
                    "w",
                    encoding="utf-8",
                    delete=False,
                    dir=destination.parent,
                    prefix=".speciedex-import-write-test.",
                ) as handle:
                    handle.write("ok\n")
                    probe = Path(handle.name)

            except OSError as error:
                raise MariaDBImportError(
                    f"Destination directory is not writable: "
                    f"{destination.parent}: {error}",
                    EXIT_CONFIGURATION,
                ) from error

            finally:
                if probe is not None:
                    probe.unlink(missing_ok=True)

    def validate_header(
        self,
        path: Path,
        result: ShardImportResult,
    ) -> None:
        first_nonempty = ""
        saw_start = False
        saw_commit = False
        header_shard_id = ""

        with open_sql_text(path) as handle:
            for line in handle:
                stripped = line.strip()
                if not stripped:
                    continue

                if not first_nonempty:
                    first_nonempty = stripped

                if stripped.casefold().startswith("-- shard_id:"):
                    header_shard_id = clean_text(
                        stripped.split(":", 1)[1]
                    )

                upper = stripped.upper()
                if upper.startswith("START TRANSACTION"):
                    saw_start = True
                elif upper.startswith("COMMIT"):
                    saw_commit = True

        result.header_ok = bool(
            SHARD_HEADER_RE.match(first_nonempty)
        )
        result.transaction_ok = saw_start and saw_commit
        result.shard_header_id = header_shard_id
        result.header_id_ok = (
            not header_shard_id
            or header_shard_id == result.shard_id
        )

        if not result.header_ok:
            self.add_issue(
                f"Invalid Speciedex shard header: {path}",
                result,
            )

        if not result.transaction_ok:
            self.add_issue(
                f"Incomplete transaction framing in shard: {path}",
                result,
            )

        if not result.header_id_ok:
            self.add_issue(
                f"Shard header id mismatch for {path}: "
                f"manifest={result.shard_id}, "
                f"header={header_shard_id}",
                result,
            )

    def reject(
        self,
        *,
        path: Path,
        shard_identifier: str,
        line_number: int,
        reason: str,
        columns: Sequence[str] | None = None,
        values: Sequence[Any] | None = None,
    ) -> None:
        self.rejected.append(
            {
                "shard_id": shard_identifier,
                "source_file": path.as_posix(),
                "line_number": line_number,
                "reason": clean_text(reason),
                "columns": list(columns or ()),
                "values": list(values or ()),
            }
        )

    def accept_record(
        self,
        record: dict[str, Any],
        result: ShardImportResult,
    ) -> None:
        record_id = clean_text(record.get("speciedex_id"))

        if not self.args.deduplicate:
            synthetic = f"@row:{len(self.record_order):020d}"
            self.records_by_id[synthetic] = record
            self.record_order.append(synthetic)
            self.total_accepted_rows += 1
            return

        if not record_id:
            self.anonymous_records.append(record)
            self.total_accepted_rows += 1
            return

        if record_id not in self.records_by_id:
            self.records_by_id[record_id] = record
            self.record_order.append(record_id)
            self.total_accepted_rows += 1
            return

        result.duplicate_records += 1

        if self.args.duplicate_policy == "first":
            return

        if self.args.duplicate_policy == "last":
            self.records_by_id[record_id] = record
            return

        raise ValueError(f"duplicate speciedex_id: {record_id}")

    def import_shard(
        self,
        shard: Mapping[str, Any],
    ) -> ShardImportResult:
        started = time.monotonic()
        identifier = shard_id(shard)
        relative = shard_path(shard)

        result = ShardImportResult(
            shard_id=identifier,
            path=relative,
            manifest_records=integer_or_none(
                shard.get("records", shard.get("rows"))
            ),
            manifest_bytes=integer_or_none(shard.get("bytes")),
            manifest_sha256=clean_text(shard.get("sha256")),
        )

        if not identifier:
            self.add_issue(
                "Manifest shard is missing an id.",
                result,
            )

        if not relative:
            self.add_issue(
                f"MariaDB shard {identifier or '<unknown>'} "
                "has no path.",
                result,
            )
            result.duration_seconds = round(
                time.monotonic() - started,
                6,
            )
            return result

        path = safe_path(self.root, relative)
        result.path = path.as_posix()
        result.exists = path.is_file()

        if not result.exists:
            self.add_issue(
                f"Missing MariaDB shard: {path}",
                result,
            )
            result.duration_seconds = round(
                time.monotonic() - started,
                6,
            )
            return result

        result.actual_bytes = path.stat().st_size
        if result.manifest_bytes is not None:
            result.size_ok = (
                result.actual_bytes == result.manifest_bytes
            )
            if not result.size_ok:
                self.add_issue(
                    f"File-size mismatch for {path}: "
                    f"manifest={result.manifest_bytes}, "
                    f"actual={result.actual_bytes}",
                    result,
                )
                if self.args.strict:
                    result.duration_seconds = round(
                        time.monotonic() - started,
                        6,
                    )
                    return result

        result.actual_sha256 = sha256_file(path)
        if result.manifest_sha256 and self.args.verify_checksums:
            result.checksum_ok = (
                result.actual_sha256.casefold()
                == result.manifest_sha256.casefold()
            )

            if not result.checksum_ok:
                self.add_issue(
                    f"Checksum mismatch: {path}",
                    result,
                )
                if self.args.strict:
                    result.duration_seconds = round(
                        time.monotonic() - started,
                        6,
                    )
                    return result

        try:
            self.validate_header(path, result)
        except (OSError, EOFError, UnicodeError) as error:
            self.add_issue(
                f"Unable to read shard {path}: {error}",
                result,
            )
            result.duration_seconds = round(
                time.monotonic() - started,
                6,
            )
            return result

        if (
            self.args.strict
            and (
                result.header_ok is False
                or result.transaction_ok is False
                or result.header_id_ok is False
            )
        ):
            result.duration_seconds = round(
                time.monotonic() - started,
                6,
            )
            return result

        expected_columns = list(SQLITE_COLUMNS)

        try:
            for line_number, columns, values in iter_insert_rows(path):
                result.parsed_records += 1

                try:
                    result.column_order_ok = (
                        columns == expected_columns
                    )
                    if not result.column_order_ok:
                        raise ValueError(
                            "column order differs from canonical "
                            "SQLITE_COLUMNS"
                        )

                    record = normalize_imported_record(
                        columns,
                        values,
                    )
                    validation_errors = validate_canonical_record(
                        record
                    )
                    if validation_errors:
                        raise ValueError(
                            "; ".join(validation_errors)
                        )

                    self.accept_record(record, result)
                    result.imported_records += 1

                except Exception as error:
                    result.rejected_records += 1
                    self.reject(
                        path=path,
                        shard_identifier=identifier,
                        line_number=line_number,
                        reason=str(error),
                        columns=columns,
                        values=values,
                    )

                    if self.args.strict:
                        raise MariaDBImportError(
                            f"{path}:{line_number}: {error}"
                        ) from error

        except (
            OSError,
            EOFError,
            UnicodeError,
            ValueError,
        ) as error:
            self.add_issue(
                f"Failed parsing shard {path}: {error}",
                result,
            )
            if self.args.strict:
                raise MariaDBImportError(
                    f"Failed parsing shard {path}: {error}"
                ) from error

        if result.manifest_records is not None:
            result.row_count_ok = (
                result.parsed_records == result.manifest_records
            )
            if not result.row_count_ok:
                self.add_issue(
                    f"Manifest row-count mismatch for {path}: "
                    f"manifest={result.manifest_records}, "
                    f"parsed={result.parsed_records}",
                    result,
                )

        result.duration_seconds = round(
            time.monotonic() - started,
            6,
        )
        return result

    def output_records(self) -> list[dict[str, Any]]:
        records = [
            self.records_by_id[key]
            for key in self.record_order
            if key in self.records_by_id
        ]
        records.extend(self.anonymous_records)

        if self.args.sort:
            records.sort(
                key=lambda record: (
                    clean_text(record.get("speciedex_id")),
                    clean_text(record.get("record_hash")),
                    stable_json(record),
                )
            )

        return records

    def build_summary(
        self,
        records: Sequence[Mapping[str, Any]],
        exit_code: int,
    ) -> dict[str, Any]:
        elapsed = time.monotonic() - self.started

        return {
            "schema_version": 3,
            "generated_at": utc_now(),
            "status": (
                "success"
                if exit_code == EXIT_SUCCESS
                else "failed"
            ),
            "exit_code": exit_code,
            "mariadb_root": self.root.as_posix(),
            "manifest": self.manifest_path.as_posix(),
            "output": self.output.as_posix(),
            "rejected_output": self.rejected_path.as_posix(),
            "valid": not self.issues and not self.rejected,
            "duration_seconds": round(elapsed, 6),
            "duration": human_duration(elapsed),
            "options": {
                "strict": self.args.strict,
                "verify_checksums": self.args.verify_checksums,
                "verify_output": self.args.verify_output,
                "deduplicate": self.args.deduplicate,
                "duplicate_policy": self.args.duplicate_policy,
                "sort": self.args.sort,
                "fail_on_issue": self.args.fail_on_issue,
                "dry_run": self.args.dry_run,
            },
            "totals": {
                "shards": len(self.results),
                "parsed_records": sum(
                    result.parsed_records
                    for result in self.results
                ),
                "source_rows_accepted": self.total_accepted_rows,
                "output_records": len(records),
                "rejected_records": len(self.rejected),
                "duplicate_records": sum(
                    result.duplicate_records
                    for result in self.results
                ),
                "issues": len(self.issues),
            },
            "issues": self.issues,
            "shards": [
                asdict(result)
                for result in self.results
            ],
        }

    def write_outputs(
        self,
        records: Sequence[Mapping[str, Any]],
        exit_code: int,
    ) -> None:
        if self.args.dry_run:
            self.logger.info(
                "Dry run: would write %d imported and "
                "%d rejected records.",
                len(records),
                len(self.rejected),
            )
            return

        write_jsonl(
            self.output,
            records,
            gzip_output=(
                self.output.name.casefold().endswith(".gz")
            ),
        )
        write_jsonl(
            self.rejected_path,
            self.rejected,
            gzip_output=(
                self.rejected_path.name.casefold().endswith(".gz")
            ),
        )
        atomic_write_json(
            self.summary_path,
            self.build_summary(records, exit_code),
        )

    def verify_output(
        self,
        records: Sequence[Mapping[str, Any]],
    ) -> None:
        if self.args.dry_run or not self.args.verify_output:
            return

        imported = verify_jsonl_count(self.output)
        if imported != len(records):
            raise MariaDBImportError(
                f"Output count mismatch: "
                f"expected={len(records)}, actual={imported}"
            )

        rejected = verify_jsonl_count(self.rejected_path)
        if rejected != len(self.rejected):
            raise MariaDBImportError(
                f"Rejected output count mismatch: "
                f"expected={len(self.rejected)}, actual={rejected}"
            )

        try:
            summary = json.loads(
                self.summary_path.read_text(encoding="utf-8")
            )
        except json.JSONDecodeError as error:
            raise MariaDBImportError(
                f"Import summary is invalid JSON: {error}"
            ) from error

        if not isinstance(summary, Mapping):
            raise MariaDBImportError(
                "Import summary is not a JSON object."
            )

        totals = summary.get("totals")
        if not isinstance(totals, Mapping):
            raise MariaDBImportError(
                "Import summary totals must be an object."
            )

        summary_records = integer_or_none(
            totals.get("output_records")
        )
        if summary_records != len(records):
            raise MariaDBImportError(
                f"Summary output count mismatch: "
                f"summary={summary_records}, "
                f"actual={len(records)}"
            )

    def run(self) -> int:
        self.configure_logging()
        records: list[dict[str, Any]] = []
        exit_code = EXIT_SUCCESS

        try:
            self.validate()
            manifest = load_manifest(self.manifest_path)
            manifest_errors = validate_manifest(manifest)
            if manifest_errors:
                raise MariaDBImportError(
                    "Invalid MariaDB manifest: "
                    + "; ".join(manifest_errors),
                    EXIT_CONFIGURATION,
                )

            kind = clean_text(manifest.get("kind"))
            if kind and kind != "mariadb-logical":
                raise MariaDBImportError(
                    "Manifest kind must be 'mariadb-logical', "
                    f"found: {kind}",
                    EXIT_CONFIGURATION,
                )

            compression = clean_text(
                manifest.get("compression")
            ).casefold()
            if compression and compression != "gzip":
                raise MariaDBImportError(
                    "Unsupported MariaDB shard compression: "
                    f"{compression}",
                    EXIT_CONFIGURATION,
                )

            shards = manifest.get("shards", [])
            if not isinstance(shards, list):
                raise MariaDBImportError(
                    "MariaDB manifest shards must be an array.",
                    EXIT_CONFIGURATION,
                )

            seen_shard_ids: set[str] = set()
            seen_paths: set[str] = set()

            for position, shard in enumerate(shards, 1):
                if not isinstance(shard, Mapping):
                    self.add_issue(
                        f"Manifest shard {position} is not an object."
                    )
                    continue

                identifier = shard_id(shard)
                relative = shard_path(shard)

                if identifier and identifier in seen_shard_ids:
                    self.add_issue(
                        f"Duplicate manifest shard id: {identifier}"
                    )
                    continue

                if relative and relative in seen_paths:
                    self.add_issue(
                        f"Duplicate manifest shard path: {relative}"
                    )
                    continue

                if identifier:
                    seen_shard_ids.add(identifier)
                if relative:
                    seen_paths.add(relative)

                result = self.import_shard(shard)
                self.results.append(result)

            records = self.output_records()

            if self.issues and self.args.fail_on_issue:
                exit_code = EXIT_INVALID

            self.write_outputs(records, exit_code)
            self.verify_output(records)

        except KeyboardInterrupt:
            self.logger.error("MariaDB import interrupted.")
            return EXIT_INTERRUPTED

        except MariaDBImportError as error:
            exit_code = error.exit_code
            self.logger.error("%s", error)

            if not self.args.dry_run:
                try:
                    records = self.output_records()
                    atomic_write_json(
                        self.summary_path,
                        self.build_summary(records, exit_code),
                    )
                except Exception:
                    pass

            return exit_code

        except Exception as error:
            exit_code = EXIT_CONFIGURATION
            self.logger.error(
                "MariaDB import failed: %s",
                error,
            )
            if self.args.verbose:
                self.logger.exception("Detailed failure")

            if not self.args.dry_run:
                try:
                    records = self.output_records()
                    atomic_write_json(
                        self.summary_path,
                        self.build_summary(records, exit_code),
                    )
                except Exception:
                    pass

            return exit_code

        if exit_code != EXIT_SUCCESS:
            for issue in self.issues:
                self.logger.error("%s", issue)
            return exit_code

        self.logger.info(
            "Imported %d records from %d MariaDB logical "
            "shard(s) with %d rejected records in %s.",
            len(records),
            len(self.results),
            len(self.rejected),
            human_duration(time.monotonic() - self.started),
        )
        return EXIT_SUCCESS


def parse_args(
    argv: Sequence[str] | None = None,
) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Import manifest-managed Speciedex MariaDB logical "
            "shards into a canonical review JSONL stream."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "--mariadb-root",
        type=Path,
        default=DEFAULT_MARIADB_ROOT,
        help="Directory containing logical SQL shards and manifest.json.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="MariaDB shard manifest; defaults to root/manifest.json.",
    )
    parser.add_argument(
        "--allow-external-manifest",
        action="store_true",
        help="Allow --manifest to be outside --mariadb-root.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Canonical imported JSONL destination.",
    )
    parser.add_argument(
        "--rejected",
        type=Path,
        default=DEFAULT_REJECTED,
        help="Rejected-row JSONL destination.",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=DEFAULT_SUMMARY,
        help="Import-summary JSON destination.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Stop on checksum, framing, parsing, or validation errors.",
    )
    parser.add_argument(
        "--verify-checksums",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Verify shard SHA-256 checksums when present.",
    )
    parser.add_argument(
        "--verify-output",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Re-read generated JSONL outputs and verify counts.",
    )
    parser.add_argument(
        "--deduplicate",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Deduplicate records by speciedex_id.",
    )
    parser.add_argument(
        "--duplicate-policy",
        choices=("first", "last", "error"),
        default="last",
        help="Policy applied when deduplication finds duplicate IDs.",
    )
    parser.add_argument(
        "--sort",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Sort output deterministically.",
    )
    parser.add_argument(
        "--fail-on-issue",
        action="store_true",
        help="Return nonzero when nonfatal issues were recorded.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse and validate without writing output files.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress informational logging.",
    )

    args = parser.parse_args(argv)

    if args.verbose and args.quiet:
        parser.error(
            "--verbose and --quiet cannot be used together."
        )

    if not args.deduplicate and args.duplicate_policy != "last":
        parser.error(
            "--duplicate-policy only applies when --deduplicate is enabled."
        )

    return args


def main(argv: Sequence[str] | None = None) -> int:
    return MariaDBImporter(parse_args(argv)).run()


if __name__ == "__main__":
    raise SystemExit(main())
